---
title: "Housing analysis, August 11th 2023"
output: 
  html_document:
    css: Wil_style.css
    theme: default
    toc: TRUE
    toc_float: TRUE
    number_sections: TRUE
always_allow_html: yes
---

```{r setup_1, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(gglaplot)
library(ggplot2)
library(data.table)
library(lubridate)
library(tidyr)
library(png)
library(stringr)
library(tidyverse)
library(plotly)
library(sf)
library(scales)
library(htmlwidgets)
library(ggplot2)
library(gglaplot)
library(ggrepel)


#devtools::load_all("C:/demogtools/")

data_dir <- 'C:/Families/Data/'
#colour_palette <- gla_colour_palette()[c(3,6,2,4,5,7,1)]


```



```{r setup_2, include=FALSE}
#--------------------------------------------------------------------------------


LondonHousingData <- read.csv("C:/Families/Data/Dashboard_housingData_Aug23.csv") %>%  
 data.frame()

#summary(LondonHousingData$Prop_Nos)

```

# Current geographical variation


```{r fig_London_Rents_1, fig.height = 5, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}


## Interactive map of rentals in 2022 in London

# Import LA boundaries for England and Wales
borough_boundaries <-
  st_read("C:/Migration/Migration_R/DATA/Domestic/copied_from_Qdrive_20220614/geographical/LAD_DEC_2021_GB_BUC.shp", quiet = TRUE)


# Match boundary data with SMA data and create categories for mapping

LondonHousingData_geog <- LondonHousingData %>% 
  left_join(borough_boundaries, by=c("BoroughCode"="LAD21CD")) %>%
  mutate(Rentals_Cat = cut(Prop_Nos, breaks = c(20, 250, 450, 650, 3000),
                             right=FALSE,
                             labels = c("  15 - 249",
                                        " 250 - 449",
                                        " 450 - 649",
                                        " 650 - 3000"))) %>%
  data.frame()

catgreen4 = c('#eeeeee', '#acc1aa', '#739272', '#4a6349')

London_Rentals_abs_map <- LondonHousingData_geog %>%
  ggplot()+
  geom_point(aes(x=BNG_E, y=BNG_N, 
                 text = paste("Borough: ", BoroughName,  
                              "<br>Properties available at LHA rate: ", 
                              formatC(Prop_Nos, format="f", big.mark=",", digits=0)
                              )),
             alpha = 0) +   # alpha = 0 ensures that points are not actually plotted
  geom_sf(aes(geometry=geometry, fill=Rentals_Cat),lwd = 0.2, colour = "black")+
  #ggla_sf()+
  #theme_gla()+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right")+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())+
  theme(plot.caption = element_text (hjust = 0))+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank())+
  scale_fill_manual(values = catgreen4) + 
  labs(title= "<b>Properties available at LHA rate, London, Summer 2022<b>", 
       caption = paste0("Source: ONS, Chart: GLA demography")) +
  labs(fill = "Availability index")

# Interactive map using ggplotly
London_Rentals_abs_map_int <- ggplotly(London_Rentals_abs_map, tooltip = "text") %>%
  layout(title= list(x = 0.05,
                     text = "<b>Properties available at LHA rate, London, Summer 2022<b>", 
                     font=list(size = 15, family = "Arial")),
         font=list(size = 14, family = "Arial", color = "black", fontface = "bold"),
         legend=list(orientation = "v", xanchor = "center", x = 1.1, y = 0.3,
                     title=list(text='Available properties',
                                font = list(family = "Arial", size = 14)),  
                     font = list(family = "Arial", size = 14))) %>%  
  # add_annotations(text="", showarrow=FALSE, legendtitle=TRUE) %>%
  layout(annotations = list(x = 0.05, y = -0.05, text = "Source: ONS; Chart: GLA demography", 
                            showarrow = F, xref='paper', yref='paper', 
                            font=list(size=14, family = "Arial")), 
         margin = list(l = 0,r = 0,  b =40,  t = 70,  pad = 4)) 
London_Rentals_abs_map_int

```
```{r fig_London_Rents_2, fig.height = 5, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}


## Interactive map of rentals in 2022 in London

# Import LA boundaries for England and Wales
borough_boundaries <-
  st_read("C:/Migration/Migration_R/DATA/Domestic/copied_from_Qdrive_20220614/geographical/LAD_DEC_2021_GB_BUC.shp", quiet = TRUE)


# Match boundary data with SMA data and create categories for mapping

LondonHousingData_geog <- LondonHousingData %>% 
  left_join(borough_boundaries, by=c("BoroughCode"="LAD21CD")) %>%
  mutate(Rentals_Cat = cut(Prop_Rate, breaks = c(15, 100, 160, 260, 1000),
                             right=FALSE,
                             labels = c("  15 - 99",
                                        " 100 - 159",
                                        " 160 - 259",
                                        " 260 - 1000"))) %>%
  data.frame()

catgreen4 = c('#eeeeee', '#acc1aa', '#739272', '#4a6349')

London_Rentals_adj_map <- LondonHousingData_geog %>%
  ggplot()+
  geom_point(aes(x=BNG_E, y=BNG_N, 
                 text = paste("Borough: ", BoroughName,  
                              "<br>Properties available at LHA rate: ", 
                              formatC(Prop_Nos, format="f", big.mark=",", digits=0),
                              "<br>Estimated borough populatioh: ", 
                              formatC(MYE_Total_Pop_2021, format="f", big.mark=",", digits=0),
                              "<br>Properties available adjusted for population: ", 
                              formatC(Prop_Rate, format="f", big.mark=",", digits=0))),
             alpha = 0) +   # alpha = 0 ensures that points are not actually plotted
  geom_sf(aes(geometry=geometry, fill=Rentals_Cat),lwd = 0.2, colour = "black")+
  #ggla_sf()+
  #theme_gla()+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right")+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())+
  theme(plot.caption = element_text (hjust = 0))+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank())+
  scale_fill_manual(values = catgreen4) + 
  labs(title= "<b>Properties available at LHA rate (adjusted for population), London, Summer 2022<b>", 
       caption = paste0("Source: ONS, Chart: GLA demography")) +
  labs(fill = "Availability index")

# Interactive map using ggplotly
London_Rentals_adj_map_int <- ggplotly(London_Rentals_adj_map, tooltip = "text") %>%
  layout(title= list(x = 0.05,
                     text = "<b>Properties available at LHA rate (adjusted for population) London, Summer 2022<b>", 
                     font=list(size = 15, family = "Arial")),
         font=list(size = 14, family = "Arial", color = "black", fontface = "bold"),
         legend=list(orientation = "v", xanchor = "center", x = 1.1, y = 0.3,
                     title=list(text='Availability index',
                                font = list(family = "Arial", size = 14)),  
                     font = list(family = "Arial", size = 14))) %>%  
  # add_annotations(text="", showarrow=FALSE, legendtitle=TRUE) %>%
  layout(annotations = list(x = 0.05, y = -0.05, text = "Source: ONS; Chart: GLA demography", 
                            showarrow = F, xref='paper', yref='paper', 
                            font=list(size=14, family = "Arial")), 
         margin = list(l = 0,r = 0,  b =40,  t = 70,  pad = 4)) 
London_Rentals_adj_map_int

```

